services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: Felvidcrelen.10
      MYSQL_DATABASE: flights_management
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8089
    expose:
      - 8001
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/flights_management?useUnicode=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Felvidcrelen.10
volumes:
  db-data:
